#! /bin/sh

### BEGIN INIT INFO
# Provides:          srf-ip-conn-srv
# Required-Start:    $local_fs $syslog $network
# Required-Stop:     $local_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SharkRF IP Connector Server
### END INIT INFO

PATH=/usr/sbin:/usr/bin:/sbin:/bin:/var/sharkrf/srf-ip-conn-srv
DESC="SharkRF IP Connector Server"
NAME=srf-ip-conn-srv

PIDFILE=/run/srf-ip-conn-srv/srf-ip-conn-srv.pid

DAEMON=/var/sharkrf/srf-ip-conn-srv/build/Release/srf-ip-conn-srv

DAEMON_ARGS="-c /var/sharkrf/srf-ip-conn-srv/config.json"

SCRIPTNAME=/var/sharkrf/srf-ip-conn-srv/build/Release/srf-ip-conn-srv

USER=sharkservice

. /lib/lsb/init-functions

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
	start)
		log_daemon_msg "Starting $DESC" "$NAME"
		start-stop-daemon --start --quiet --oknodo --chuid $USER \
			--exec $DAEMON -- $DAEMON_ARGS
		log_end_msg $?
		;;
	stop)
		log_daemon_msg "Stopping $DESC" "$NAME"
		start-stop-daemon --stop --quiet --oknodo --retry=TERM/15/KILL/5 --pidfile $PIDFILE \
			--name $NAME
		status=$?
		rm -f $PIDFILE
		log_end_msg $?
		;;
	status)
		pidofproc -p $PIDFILE $DAEMON >/dev/null
		status=$?

		if [ $status -eq 0 ]; then
			log_success_msg "$DESC is running"
		else
			log_failure_msg "$DESC is not running"
		fi
		exit $status
		;;
	reconfigure)
		killall -HUP srf-ip-conn-srv
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: $SCRIPTNAME {start|stop|restart|status|reconfigure}"
		exit 1
		;;
esac

